# Generated by Django 5.1.2 on 2025-01-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_repo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="vault_path",
        ),
    ]
