# Generated by Django 5.1.2 on 2024-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="vault_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
