# Generated by Django 5.1.2 on 2025-01-22 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0002_memo_vault_synced_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
