# Generated by Django 5.1.2 on 2025-01-22 05:19

import memos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memos", "0003_alter_memo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memo",
            name="created_at",
            field=models.DateTimeField(default=memos.models._get_current_time),
        ),
    ]
